<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>exoskeleton_dynamics_cpp</name>
  <version>0.0.0</version>
  <description>C++ port of exo reduced dynamics node with hand model</description>
  <maintainer email="mbari@todo.todo">mbari</maintainer>
  <license>TODO</license>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>exoskeleton_safety_msgs</depend>
  <depend>ament_index_cpp</depend>
  <build_depend>pinocchio</build_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
